services:
  - type: web
    name: kabque-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && gunicorn kabque.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.3"
      - key: DJANGO_SETTINGS_MODULE
        value: kabque.settings
