# Generated by Django 6.0.7 on 2026-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='programme',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
