# Generated by Django 6.0.7 on 2026-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0002_studentprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='joined_queue_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registered_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='registered_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
